### ISSUE TITLE
turn off all WiFi

### ISSUE THREAD

**Issue by vangalvin** [jbaumann/H32_Basic#2]
Hi Joachim,

Im working on a project and using the H32 as a base. I have a string of about 20 to 30 DS18B20's that will be lowered in to a bore hole in a realy remote location. I have a MicroSD card and would like to store the temperatures on to the SD. There is no sun for around 6 months in this location and there will only be one visit to the place a month after it is installed.

Due to the hostile enviroment everyting will be sealed, I will be placing a reed switch on the inside of the case so if someone visits the site and places a magnet on the switch the WiFi will start up and they can download/clear the logs. 

Other than that the idea is to start up, read the sensors, voltage etc, write that to the SD and go back to sleep.
I know there will be drift on the RTC but that should not be a problem for this project. We can estimate the offset and make a correction if need be.

Is there a way to have the unit come out of sleep, read the seonsrs, save them to the SD then go back to sleep and bypass all the wifi and connectivity code? Or would I be better off creating some code for the unit from scratch?

Any help would be greatly appreciated,

**Comment by jbaumann** [comment]
Hi Boris,

this is what I already wrote to Andrew (I assume he is your colleague):
I find this an extremely interesting use case, even though I see some potential problems/challenges.

On the hardware side:

• Are you sure that a battery is able to handle the extremely low temperatures and the power draw of the system when it takes its measurements? Even if we do not turn on the WiFi connection we are still talking about 100-200mA I think (I would have to verify the exact value). I assume each of the DS18B20 will also take 10-20 mA during measurements, which would mean a huge drain overall on the battery.
• MicroSD card: Even though I think it can handle the temperature, it will still need a lot of power when writing. And we have mechanical contacts that might suffer from low temperatures and condensation/icing over… I have absolutely no experience here…
• Instead of WiFi you could use a simple plug with 4 wires over which you could charge the battery, and transfer the data e.g. over a simple serial protocol.
• I think the FET for controlling the power to sensors and SD card is a very good approach, and the ESP would be ideal for controlling it. Remember that you need a pull-up/pull-down resistor because once the ESP is disconnected from the power the output pins are in tri-state/floating.
• I would also suggest that you use three installations instead of one (an old scientific rule: something will go wrong… multiple times)

On the software side:

• The H32 firmware is a basis from which something like this can be developed pretty easily. The extension mechanism allows to
• decide whether the WiFi is turned on at all (this is something on my list and not yet realized, but simple to implement) e.g., depending on a GPIO state (the reed switch)
• turn on and initialise the sd card and the sensors
• collect arbitrary data in a data collection stage
• send data wherever needed in the final stage (here writing to the sd card could take place)
• and all without touching the basic structure.

And if there is something missing, then I think I could add it pretty easily. But the extension mechanism is already in place, tested and simple to use. If you have a look at the LoRa-Extension that I wrote for Christos at one time you can see how easy it is to implement your own extension.

**Comment by vangalvin** [comment]
Thank you for your response Joachim,

Boris is my Nickname. About 12 years ago I was part of the New Zealand steampunk group, and everyone just referred to me as Boris (the not so evil genius) It stuck to the point where I went about 6 years without hearing my real name.

I managed to test the unit and in sleep mode we are down to about 20ua using the H32 I can reduce that a little more with the FET and dropping power to the sensors and the CF.

Wake and read without WiFi seems to be about 140ma for about 2/3 seconds and I am trying to get that down. I also may see if its worth dropping the ESP32 down to 80Mhz as that cuts the power consumption of the ESP in half.

The battery I have opted for is a INR-18650-M35A and will still operate at sub zero temperatures however the unit is mounted to a pole that is in a volcanic vent and the ground the unit is sitting on is around +30/+60 degrees C. The last unit we had on site had an internal temperature of around +4 degrees but we can not count on this so I am trying to design for the worsted case.

I had thought about a plug and looked at a few options. there were few connectors that seemed to meet the requirements and allow the team to remove the protective cover and connect without taking off the gloves. the other issue was the one we tried a few years back tended to get ice in it and freeze the cover in place.

With the H32 system looks great and I started to create an extension for the sensors and SD logging but realised that the WiFi side was quite extensive and that I really needed to trim things down.

I have a reed switch in place that has an ISR on it on IO17, when you put a magnet on the switch and leave it there the units starts in AP mode. I still need to put some code in that checks that the magnet triggers a reboot then its removed. Initially I put a reboot button on the web page but knowing researchers I can imagine them taking the magnet and forgetting to hit the button so a big magnet with a big red flight tag on it should ensure they remove it.

The code I have put together is pretty ugly, I am not exactly a coder and I would like to also thank you for some of the examples you have provided in the original firmware as they have been a huge help in conceiving this. Today I am hoping to clean up the code that requests the temperature form the DS18B20's and stores the data to a CSV or TXT file on the SD and then create a way to set the clock, adjust the alarm interval and test the power usage per cycle.

I will take a look at the Lora example, Even if I do not use the full system for this project I will be ordering in some more boards from Christos as I do have a few other pet projects that I think these and the firmware would work really well with. I'm waiting to see what Starlink do with the SWARM network as I have a few Swarm modems here. $5.00 per month for telemetry data anywhere in the world is pretty good 🙂 and the units are not too power hungry.

Once I get the code in a more functional state would you mind me sending it to you to take a look at and see if I have missed anyting?

Regards
Andrew/Boris



________________________________

**Comment by jbaumann** [comment]
Hi Boris,

I could look into the extension system and implement something like "vetoWiFi()", that, when returning true, stops the firmware from starting WiFi. The rest of the extension mechanism would still run including the normal data gathering etc.
When the method vetoWiFi() is called it could check for the presence of the magnet and return false if it is present.
When the magnet is present, should it try to log into an existing network? How should it otherwise upload the data?

And yes, please send me the code if you want. I'm very curious :-)

Cheers, Joachim

**Comment by vangalvin** [comment]
Hi Joachim,

That would be a really nice addition. I have been working on a few things this week.

I had the unit log the 34 DS19B20 sensors to an SD card and sort the temperatures in to the correct order.
Add a time and date for the data then the system would go back to sleep.

I was able to trigger an interrupt on GPIO17 and if I held that pin low the unit would start the AP and create a file list when you could log in and download the relevant log.

That all worked until last night when I for reasons I am not sure the unit would no longer respond to an interrupt request on 17.

On a more positive note, doing things this way resulted in power levels that should allow the battery to last nearly 2 years. 🙂

Andrew


________________________________

**Comment by vangalvin** [comment]
Hi Joachim,

That would be really helpful. I have been cutting the code together and trying to get this thig operating on its "bare bones"

I am seeing a time drift of from 23:35:51 last night to 8:21:22 this morning, a total of 525 minutes 31 seconds and the RTC it drifted 1 minute 31 seconds.

I'm just heading away for the weekend so will leave it running and see what happens. At present its waking every 60 seconds.

Is there a way to calibrate the RTC?

Regards
Andrew

________________________________

**Comment by jbaumann** [comment]
I added the functionality to veto the WiFi initialization and thus stop the WiFi communication altogether to the extension mechanism.
